import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { HomePage } from "../src/components/home/home-page"


export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>{data.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    

      <HomePage data={data} />

    
    </div>
  )
}


//SERVER SIDE RENDERING
// This function returns the props object which is passed to the component as props
// This function is only executed on the server side.
export async function getServerSideProps() {

  //data is our internal database
  const { events_categories } = await import('data/data.json')

  return {
    props: {
      data: events_categories,
    },
  };
}

