import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home({data}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>{data.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* add a header */}
      <header className={styles.header}>
        {/* add a navigation */}
        <nav className={styles.nav}>
          {/* add also an image tag */}
        
          
              <a href="/">Home</a>
            
              <a href="/about">About</a>
          
              <a href="/events">Events</a>
        
        </nav>
      </header>
      <main className={styles.main}>
        {/* create 3 div */}
    
          {data.map((cat) => (
            <a key={cat.id } href={`/events/${cat.id}`}>
              <Image width={200} height={'100'} alt={cat.title} src={cat.image} />
              <h2>{cat.title}</h2>
              <p>{ cat.description}</p>
            </a>
          
          ))}
      </main>

      <footer className={styles.footer}>
        {/* add a copyrigth */}
        <p>&copy; 2021 Events Next App</p>
        
      </footer>
    </div>
  )
}


//SERVER SIDE RENDERING
// This function returns the props object which is passed to the component as props
// This function is only executed on the server side.
export async function getServerSideProps() {

  //data is our internal database
  const {events_categories} = await import('data/data.json')

  return {
    props: {
  data: events_categories,
    },
  };
}

