import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Events Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* add a header */}
      <header className={styles.header}>
        {/* add a navigation */}
        <nav className={styles.nav}>
          {/* add also an image tag */}
        
          
              <a href="/">Home</a>
            
              <a href="/about">About</a>
          
              <a href="/events">Events</a>
        
        </nav>
      </header>
      <main className={styles.main}>
        {/* create 3 div */}
        <a href="" className={styles.card}>
          <h2>Event in London &rarr;</h2>
          {/* add some little description like lorem ipsum */}
          <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Aliquam voluptatum nemo hic quia doloremque quibusdam deserunt magni fugiat animi voluptas nam ex, sunt consectetur recusandae voluptatem eius quam consequatur laborum.</p>
        </a>
        <a href="" className={styles.card}>
          <h2>Event in San francisco &rarr;</h2>
          <p>Find in-depth information about Next.js features and API.</p>
        </a>
        <a href="" className={styles.card}>
          <h2>Event in Paris &rarr;</h2>
          <p>Find in-depth information about Next.js features and API.</p>
        </a>

      </main>

      <footer className={styles.footer}>
        {/* add a copyrigth */}
        <p>&copy; 2021 Events Next App</p>
        
      </footer>
    </div>
  )
}
